label END_unknowntrue:
    window auto
    scene black
    with fade
    $ daynum = "67"
    $ dayday = "Home"

    if renpy.is_skipping() == False:
        show screen truedaytransition
        $ renpy.pause(2.0, hard=True)
    
    scene black with fade
    play music deathtoaperture
    n "You sigh."
    n "Another day, another dollar."
    n "And today isn't any different."
    n "But that's not the part of your day you most look forward to, anymore..."
    n "You turn the key in your lock and open the door."
    scene apt one with fade
    mc "I'm home."
    n "There's no response, though that's nothing new."
    n "He tends to be quieter recently - lots of introspection to do."
    n "You put down your bag, take off your shoes, and round the corner."
    mc "Hey, Ryland."
    show u offrail with easeinbottom
    ry "Ah! Sorry, I, uh..."
    ry "I didn't hear you come in."
    mc "Any new developments today?"
    ry "I had a bit of a breakthrough..."
    ry "Nothin' spectacular, but it's better than nothing."
    mc "Oh yeah? What was it?"
    ry "I remembered my original job. Y'know, what I was before I was cut from the system."
    mc "That's not \"spectacular\" to you?! That's huge!"
    ry "Hah... I guess."
    mc "Well? What was your job?"
    mc "If you don't mind telling, of course."
    ry "I was a... a maintenance technician, funny 'nough."
    ry "Lower system stuff, though. Pipes and water systems..."
    ry "Makin' sure there wasn't any cracks, y'know?"
    mc "Sounds rough."
    ry "Y-Yeah, I think that mighta had somethin' to do with... how I got to... {i}that{/i} point."
    mc "Ryland, you don't have to talk about that if you -"
    ry "Nah, nah. It's fine. It... helps. To talk about it."
    ry "Reminds me how far I've come."
    mc "That's good."
    n "You sit down next to him."
    n "Life's been slow since the two of you escaped Aperture."
    n "It was tough at first -"
    n "The lack of Aperture-brand lighter fluid made Ryland's recovery difficult."
    n "He'd only recently stopped having withdrawal symptoms."
    n "You look down at him."
    mc "How are you feeling? Anything internally?"
    ry "Mmm... not that I can tell. No new systems breaks, if that's what you're askin'."
    ry "Can't believe you still remember all that training..."
    mc "I {i}was{/i} in Manufacturing for, what, nine months?"
    mc "I built so many cores down there."
    mc "You're honestly surprised I know them inside and out?"
    ry "Hah... guess not."
    ry "Still... it prolly ain't easy caring for me all the time."
    mc "It's worth it."
    mc "You've grown so much, Ryland."
    ry "And it's only been two months."
    ry "Ha! Imagine how much more you got ahead of ya to deal with..."
    mc "I think I'm ready."
    n "The two of you sit on the couch in silence for a bit."
    n "You've gotten used to the rhythmic clanking of Ryland's internals -"
    n "A little rougher than the average Aperture core, but a sign that he's still running, nonetheless."
    n "It's reassuring."
    n "And a little soothing at night."
    ry "..."
    mc "..."
    ry "Ain't it a little weird sometimes?"
    mc "What?"
    ry "You... and me. Y'know. Human and robot."
    ry "Whaddaya tell people at work? \"My boyfriend\"?"
    mc "I just say my \"partner.\""
    ry "And what about when they ask what I look like?"
    mc "I tell them the truth."
    mc "Or... a version of it."
    mc "Is it really a lie to tell them you've got coffee-colored eyes and a few scars on your body?"
    ry "I mean... kinda. Optics and metal patch plates, but..."
    ry "I guess it's kinda the same, huh?"
    mc "..."
    ry "..."
    mc "Do you want to go out to the balcony?"
    ry "Yeah. I think I'd like that."
    mc "Let me go grab a drink and we'll go out together."

    scene black with fade
    scene apt balcony with fade
